sudo: required
dist: trusty

language: node_js
node_js:
- '6'

before_deploy:
- npm install -g serverless
- npm install
- touch .env
- echo "MAILCHIMP_USERNAME=\$MAILCHIMP_USERNAME\"" >> .env
- echo "MAILCHIMP_API_KEY=\"$MAILCHIMP_API_KEY\"" >> .env
- echo "MAILCHIMP_API_URI=\"$MAILCHIMP_API_URI\"" >> .env

deploy:
- sls deploy --stage prod